### ISSUE TITLE
PolarCloud - not updated after stop print

### ISSUE THREAD

**Issue by ClueControl** [markwal/OctoPrint-PolarCloud#44]
I use the STOP button on the polar3d.com website to stop a print mid print (28.4% complete).  

After the stop command, Polar3d.com no longer showed updates from the camera or the temperatures.  

The attached screen shot was taken several hours after the print was stopped.  I have visually confirmed that the bed and extruder are at ambient temperature, and the room is dark, there should be no image.

![image](https://user-images.githubusercontent.com/22554740/48151995-be428a80-e290-11e8-93ae-3cc2eed308cb.png)

**Comment by kg4iae** [comment]
I'm having the same issue.  It's not ideal, but if you go to Octoprint, and restart it, Polar will cancel the job.  Also, note, that doing the Restart in Polar will restart Octoprint but it will not clear the current job..

**Comment by markwal** [comment]
Hmmm...  Currently don't repro this behavior (yet).  What printer firmware are y'all using (@ClueControl , @kg4iae) and is there anything interesting (exception or error) in your octoprint.log?

**Comment by markwal** [comment]
I have a theory.  If timelapse generation (it takes a while after print completion and/or cancel) or upload fails, it doesn't return to ready mode.  Perhaps this happens when there is a problem with the Pillow package install or when folks have opted not to install the timelapse packages (they're optional, the plugin doesn't install them since they're system packages not python packages, without them there's no timelapse upload to Polar Cloud).

**Comment by markwal** [comment]
Hopefully fixed in 1.7
